spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddd?characterEncoding=utf8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

    jpa:
      database: mysql
      show-sql: true
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      open-in-view: false

logging.level:
  root: info
  com.learn: debug
  org.springframework:
    security: debug